.TH LPASS 1 "4 JULY 2021" "LPASS v1.2a" LockPassword

.SH NAME
LockPassword - a password manager.

.SH SYNOPSIS
.B lpass
.RI < command >
.RI [< options >]

.SH DESCRIPTION
.B lpass
- a simple terminal password manager, using GnuPG to encrypt passwords.

.SH COMMANDS

.B init
.RI < gpg-key >
.RS 4
Initialize the password manager using the passed \fIgpg-key\fR as the encryption key. This command must be run first before you start working with LockPassword.
.RE

.B insert
.RB [ "-e, --echo" ]
.RB [ "-c, --copy" ]
.RB [ "-f, --force" ]
.RI < passname >
.RS 4
Add the specified \fIpassname\fR to the password manager. The password will be read interactively using standard input, character display is hidden. The \fB-e, --echo\fR argument enable the show of characters when typing a password; \fB-c, --copy\fR write password to clipboard; \fB-f, --force\fR ignore exist of \fIpassname\fR, overwrites it without prompt.
.RE

.B show
.RB [ "-c, --copy" ]
.RB [ "-C, --no-color ]
.RI < passname >
.RS 4
If no \fIpassname\fR is specified, \fIpassname\fR will assign root of password manager tree. If \fIpassname\fR is directory, list names of passwords inside the at \fIpassname\fR. Otherwise decrypt and print a password of \fIpassname\fR. The \fB-c, --copy\fR write password to clipboard; \fB-C, --no-color\fR cancel colorize the output.
.RE

.B edit
.RI < passname >
.RS 4
Open the specified \fIpassname\fR in a text editor, waiting for changes. The text editor specified in the environment variable EDITOR or \fBvi\fR(1) is used. Temporary file for password editing locate in tmpfs / ramfs (we expect that it to be mounted at /dev/shm).
.RE 

.B generate
.RB [ "-l, --length" =pass-length]
.RB [ "-c, --copy" ]
.RB [ "-f, --force" ]
.RI < passname >
.RS 4
Generate a random password and write it in \fIpassname\fR. The \fB-l, --length = pass-length\fR argument allow you to specify the desired password length. Without this argument, a 14 character password will be generated. \fB-c, --copy\fR write password to clipboard; \fB-f, --force\fR ignore exist of \fIpassname\fR, overwrites it without prompt.
.RE

.B mv
.RB [ "-f, --force" ]
.RI < old-path "> <" new-path >
.RS 4
Move/rename \fIold-path\fR to \fInew-path\fR. \fIold-path\fR must be an exist file, \fInew-path\fR can be a file/directory. The \fB-f, --force\fR argument ignore exist of \fInew-path\fR (if it's a file), overwrites it without prompt.
.RE

.B rm
.RI < passname >
.RS 4
Remove the \fIpassname\fR you specified from the password manager. If the directories where your \fIpassname\fR was nested became empty after deletion, then they are also deleted.
.RE

.B help
.RS 4
Print help information about commands and the application itself.
.RE

.B version
.RS 4
Print information about the version, release date, and license of the application.
.RE

.SH EXAMPLES
Initialize the password manager:
.RS 4
.B $ lpass init joursoir@joursoir.net
.br
LockPassword initialized for joursoir@joursoir.net
.br
.RE

Add password in the password manager:
.RS 4
.B $ lpass insert games/chess/user
.br
Please type your new password: [invisible input]
.br
Please type your new password again: [invisible input]
.br
Password added successfully for games/chess/user
.RE

Print a list of exists password:
.RS 4
.B $ lpass show
.br
Password Manager
.br
\[u251C]\[u2500]\[u2500] banks
.br
\[u2502]   \[u251C]\[u2500]\[u2500] abankpro
.br
\[u2502]   \[u2502]   \[u2514]\[u2500]\[u2500] phone_number
.br
\[u2502]   \[u2514]\[u2500]\[u2500] ubank
.br
\[u2502]       \[u2514]\[u2500]\[u2500] phone_number
.br
\[u2514]\[u2500]\[u2500] games
.br
    \[u2514]\[u2500]\[u2500] chess
.br
        \[u251C]\[u2500]\[u2500] site.com
.br
        \[u2514]\[u2500]\[u2500] user
.RE

Print a list of exists password in some directory:
.RS 4
.B $ lpass show banks
.br
Password Manager/banks
.br
\[u251C]\[u2500]\[u2500] abankpro
.br
\[u2502]   \[u2514]\[u2500]\[u2500] phone_number
.br
\[u2514]\[u2500]\[u2500] ubank
.br
    \[u2514]\[u2500]\[u2500] phone_number
.RE

Show password:
.RS 4
.B $ lpass show games/iko/LordOfNight
.br
helloitismypassword123
.RE

Copy password to clipboard:
.RS 4
.B $ lpass show -c games/iko/LordOfNight
.RE

Generate password:
.RS 4
.B $ lpass generate bank/sbank/phone_number
.br
Generated password: NsNu:+^Re(cshW
.br
Password added successfully for bank/sbank/phone_number
.RE

.SH "COPYING"
Copyright (C) 2020-2021 Aleksandr D. Goncharov (Joursoir)
.br
License: GNU GPL version 3
.br
This is free software: you are free to change and redistribute it. This program comes with ABSOLUTELY NO WARRANTY.
