.TH "LPASS" "1" "6\ \&MARCH\ \&2021" "LPASS v1.1b" "LockPassword"

.SH "NAME"
LockPassword - a password manager.

.SH "SYNOPSIS"
\fBlpass\fR [command] [options]

.SH "DESCRIPTION"
\fBlpass\fR - a simple terminal password manager, using GnuPG to encrypt passwords.

.SH "COMMANDS"
\fBinit \fIgpg-key\fR
.RS 4
Initialize the password manager using the passed \fIgpg-key\fR as the encryption key. This command must be run first before you start working with LockPassword.
.RE
.PP

\fBinsert\fR [-e, --echo] [-c, --copy] [-f, --force] \fIpassname\fR
.RS 4
Add the specified \fIpassname\fR to the password manager. The password will be read interactively using standard input, character display is hidden. The \fB-e, --echo\fR argument enable the show of characters when typing a password; \fB-c, --copy\fR write password to clipboard; \fB-f, --force\fR ignore exist of \fIpassname\fR, overwrites it without prompt.
.RE
.PP

\fBedit \fIpassname\fR
.RS 4
Open the specified \fIpassname\fR in a text editor, waiting for changes. The text editor specified in the environment variable EDITOR or \fBvi\fR(1) is used. Temporary file for password editing locate in tmpfs / ramfs (we expect that it to be mounted at /dev/shm).
.RE
.PP 

\fBgenerate\fR [-l, --length=pass-length] [-c, --copy] [-f, --force] \fIpassname\fR
.RS 4
Generate a random password and write it in \fIpassname\fR. The \fB-l, --length = pass-length\fR argument allow you to specify the desired password length. Without this argument, a 14 character password will be generated. \fB-c, --copy\fR write password to clipboard; \fB-f, --force\fR ignore exist of \fIpassname\fR, overwrites it without prompt.
.RE
.PP

\fBmv\fR [-f, --force] \fIold-path new-path\fR
.RS 4
Move/rename \fIold-path\fR to \fInew-path\fR. \fIold-path\fR must be an exist file, \fInew-path\fR can be a file/directory. The \fB-f, --force\fR argument ignore exist of \fInew-path\fR (if it's a file), overwrites it without prompt.
.RE
.PP

\fBrm \fIpassname\fR
.RS 4
Remove the \fIpassname\fR you specified from the password manager. If the directories where your \fIpassname\fR was nested became empty after deletion, then they are also deleted.
.RE
.PP

\fBhelp\fR
.RS 4
Print help information about commands and the application itself.
.RE
.PP

\fBversion\fR
.RS 4
Print information about the version, release date, and license of the application.
.RE
.PP

.SH "EXAMPLES"
Initialize the password manager:
.RS 4
\fB$ lpass init joursoir@joursoir.net\fR
.br
LockPassword initialized for joursoir@joursoir.net
.br
.RE
.PP

Add password in the password manager:
.RS 4
\fB$ lpass insert games/chess/user\fR
.br
Please type your new password: [invisible input]
.br
Please type your new password again: [invisible input]
.br
Password added successfully for games/chess/user
.RE
.PP

Print a list of exists password:
.RS 4
\fB$ lpass\fR
.br
Password Manager
.br
|-- banks
.br
|   |-- abankpro
.br
|   |   `-- phone_number
.br
|   `-- ubank
.br
|       `-- phone_number
.br
`-- games
.br
    `-- chess
.br
        |-- site.com
.br
        `-- user
.RE
.PP

Print a list of exists password in some directory:
.RS 4
\fB$ lpass banks\fR
.br
Password Manager/banks
.br
|-- abankpro
.br
|   `-- phone_number
.br
`-- ubank
.br
    `-- phone_number
.RE
.PP

Show password:
.RS 4
\fB$ lpass games/iko/LordOfNight\fR
.br
helloitismypassword123
.RE
.PP

Copy password to clipboard:
.RS 4
\fB$ lpass -c games/iko/LordOfNight
.RE
.PP

Generate password:
.RS 4
\fB$ lpass generate bank/sbank/phone_number\fR
.br
Generated password: NsNu:+^Re(cshW
.br
Password added successfully for bank/sbank/phone_number
.RE
.PP

.SH "COPYING"
Copyright (C) 2020-2021 Aleksandr D. Goncharov (Joursoir)
.br
License: GNU GPL version 3
.br
This is free software: you are free to change and redistribute it. This program comes with ABSOLUTELY NO WARRANTY.
